### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by benhaynes** [directus/voting-tool#11]
The title edit input is truncated for no reason... shouldn't be
![screen shot 2017-09-26 at 6 24 02 pm](https://user-images.githubusercontent.com/522079/30887094-e18ce06a-a2e7-11e7-89a1-91d6e8400a23.png)

The "CHECK MARK" in the design was for ADMINS marking the item as complete. We can use it for this, but then we need something for "COMPLETE". 

- [x] We need a "CANCEL" button when editing.
- [x] Can we move the "EDIT" title button to the end of the `Created 1 year ago by benhaynes • edit` line?
- [x] Let's use the CHECK MARK for saving new and existing comments instead of the SEND arrow

**Comment by rijkvanzanten** [comment]
The checkmark for admin point is a _wontfix_, as admins manage the content through the Directus instance
