### ISSUE TITLE
Markup and SEO

### ISSUE THREAD

**Issue by benhaynes** [directus/voting-tool#2]
Also, I noticed that this page doesn't have a `<html||head||body>`... we should get this SEO friendly so people can find it.

Also should have all metadata, twitter cards, icons, favicons, etc (see current site)

**Comment by WellingGuzman** [comment]
It seems it has `html/head/body` here [app/views/partials/head.ejs](https://github.com/directus/voting-tool/blob/master/app/views/partials/head.ejs)

Although not metadata twitter card,etc

**Comment by rijkvanzanten** [comment]
This isn't a bug, but a feature:

https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags

**Comment by benhaynes** [comment]
OK weird.

Well then let's just get it SEO/Social performant

**Comment by WellingGuzman** [comment]
I was going to say that Rijk is by the book with these solution, because browser are smart adding this optionals thing.

Like I said that doesn't mean we shouldn't add them ;)
