### ISSUE TITLE
Responsive Tweaks

### ISSUE THREAD

**Issue by benhaynes** [directus/voting-tool#21]
- [x] The GitHub username overlaps the toggles around 700px

- [x] Toggle buttons should be split 50/50 (right now they're not even)

- [x] SUGGEST should become 100% width with the GH name BELOW it

- [x] ONLY ON RESPONSIVE: Decrease the spacing above toggles (description) and increase below SUGGEST. 

- [x] Adjust body padding to 1.5em

## DETAIL PAGE

- [x] Add a comment here is not vertically centered

- [x] Too much spacing between BACK TO LISTING and LOGO

- [ ] Center BACK TO LISTING link

**Comment by rijkvanzanten** [comment]
I wasn't 100% on what you meant with "Center BACK TO LISTING link", so I went with this. Please confirm if this what you were referring to @benhaynes. If not, I'll revert it.

_Before:_
<img width="1172" alt="screen shot 2017-10-03 at 4 49 23 pm" src="https://user-images.githubusercontent.com/9141017/31148551-0841d1a2-a85b-11e7-9fc3-bb9dc081eedd.png">


_After:_
<img width="1173" alt="screen shot 2017-10-03 at 4 50 08 pm" src="https://user-images.githubusercontent.com/9141017/31148550-0832b47e-a85b-11e7-8bc7-74744584e2df.png">

**Comment by benhaynes** [comment]
Yes, but ONLY for responsive... it should still be on the left for larger viewports.

**Comment by rijkvanzanten** [comment]
Gotcha, updating now..
