### ISSUE TITLE
Ordering by date bugs

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/voting-tool#22]
It sorts on something..., but it certainly isn't last_updated

**Comment by rijkvanzanten** [comment]
Problem: not every item has last_updated set, since not every item is edited. Changing to ordering on creation date

**Comment by benhaynes** [comment]
Creation date for the parent? That's fine for now... but eventually we want this to sort by most recent creation of the parent/comment.

**Comment by rijkvanzanten** [comment]
We could maybe sort on the creation date of the last comment added to a particular request. That'll order by most "active"
