### ISSUE TITLE
Horizontal scrolling in comment

### ISSUE THREAD

**Issue by benhaynes** [directus/voting-tool#24]
Let's update the CSS to break word, or some other attribute to avoid this:

https://request.getdirectus.com/r/10

**Comment by rijkvanzanten** [comment]
On code snippets? I kinda added that in as a feature, not a bug, as I didn't want to hyphenate / break code snippets

**Comment by benhaynes** [comment]
That's fine – but the SNIPPET should scroll within the `code` element, not the entire comment. Let's see how GH does it:

```
{ id: 1, sort: 1, parentid: 1, related_table: 'varchar', related_id: 1, data: { title: "My Matrix Title" } }, { id: 2, sort: 2, parent_id: 1, related_table: 'text', relatedid: 1, data: { text: "Lorem ipsum dolor et..." } }, { id: 3, sort: 3, parentid: 1, relatedtable: 'image', related_id: 1, data: { image: 1, data: { url: "my-file.jpg" } } }
```
