### ISSUE TITLE
Filters and Signup

### ISSUE THREAD

**Issue by benhaynes** [directus/voting-tool#3]
Let's make the GITHUB login Blue

Filter Toggles should have pointer and hover states... after clicking, the screen should SMOKE (fixed fullscreen gray overlay with 0.8 opacity and "waiting" cursor) to show it's loading.

**Comment by rijkvanzanten** [comment]
https://github.com/directus/voting-tool/issues/5

**Comment by benhaynes** [comment]
We can still instantly add a SMOKE on click... then it will auto disappear when the new page loads. But as of now, it sits on the current page for a while and looks stalled.
